apiVersion: v1
kind: Service
metadata:
  name: certification-authority-svc
  labels:
    run: certification-authority-svc
spec:
  type: ClusterIP
  selector:
    name: ca
  ports:
  - protocol: TCP
    port: 30054
    targetPort: 7054
    name: grpc
  - protocol: TCP
    port: 7054
    name: grpc1