apiVersion: v1
kind: Service
metadata:
  name: org3peer1-svc
  labels:
    run: org3peer1-svc
spec:
  type: ClusterIP 
  selector:
    name: org3peer1
  ports:
  - protocol: TCP
    port: 30110
    name: grpc
  - protocol: TCP
    port: 30111
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb