kind: ConfigMap 
apiVersion: v1 
metadata:
  name: peer-configmap 
data:
  TZ: "Asia/Jerusalem"
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_NETWORKID: nid1
  CORE_PEER_LISTENADDRESS: 0.0.0.0:30110
  CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:30111
  CORE_PEER_GOSSIP_ORGLEADER: "false"
  CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"
  CORE_PEER_GOSSIP_USELEADERELECTION: "true"
  CORE_PEER_COMMITTER_ENABLED: "true"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
  CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN: "pbft"
  CORE_PBFT_GENERAL_MODE: "classic"
  CORE_PBFT_GENERAL_N: "4"
  CORE_LOGGING_LEVEL: debug
  CORE_LOGGING_PEER: debug
  CORE_LOGGING_CAUTHDSL: debug
  CORE_LOGGING_GOSSIP: debug
  CORE_LOGGING_LEDGER: debug
  CORE_LOGGING_MSP: info
  CORE_LOGGING_POLICIES: debug
  CORE_LOGGING_GRPC: debug
  CORE_PEER_TLS_ENABLED: "false"
  CORE_LEDGER_STATE_STATEDATABASE: "CouchDB"
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: "localhost:5984"
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: "hyperledgeruser"
  CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: "hyperledgerpass"
  FABRIC_CFG_PATH: /etc/hyperledger/fabric/
  ORDERER_URL: orderer:31010
  GODEBUG: "netdns=go"
  CORE_VM_DOCKER_ATTACHSTDOUT: "true"